# Generated by Django 4.0.4 on 2022-07-02 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir_model', '0003_alter_complaint_assign_by_alter_complaint_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add2', to='fir_model.additionalinfo'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assign_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cissues1', to='fir_model.customerissue'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer_raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fir_model.customer'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fir_model.resolutiontype'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tracker',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
