# Generated by Django 4.0.4 on 2022-07-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_model', '0004_alter_complaint_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isuser',
            options={'verbose_name_plural': 'ISUSER'},
        ),
    ]
