# Generated by Django 4.0.4 on 2022-07-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_model', '0005_alter_isuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='soft_pack_serial_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
