# Generated by Django 4.0.4 on 2022-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_model', '0006_complaint_soft_pack_serial_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerRaisedBy',
        ),
    ]
