# Generated by Django 4.0.4 on 2022-07-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_model', '0007_rename_customer_customerraisedby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerraisedby',
            options={'verbose_name_plural': 'CUSTOMER Raised By'},
        ),
    ]
